// Add this to your existing constants
export const blogPosts = [
  {
    id: 1,
    title: "The Evolution of Modern Football Tactics",
    excerpt:
      "Exploring how tactical innovations have shaped the beautiful game and continue to influence modern football strategies.",
    image: "/optimized/blog/tactics/tactics1-large.webp",
    imageFallback: "/optimized/blog/tactics/tactics1-large.jpg",
    thumbnail: "/optimized/blog/tactics/tactics1-small.webp",
    thumbnailFallback: "/optimized/blog/tactics/tactics1-small.jpg",
    category: "Tactics",
    date: "March 15, 2024",
    readTime: 5,
  },
  {
    id: 2,
    title: "Essential Recovery Techniques for Athletes",
    excerpt:
      "Discover the most effective recovery methods to maintain peak performance and prevent injuries throughout the season.",
    image: "/optimized/blog/trainings/trainings1-large.webp",
    imageFallback: "/optimized/blog/trainings/training1-large.jpg",
    thumbnail: "/optimized/blog/trainings/training1-small.webp",
    thumbnailFallback: "/optimized/blog/trainings/training1-small.jpg",
    category: "Training",
    date: "March 12, 2024",
    readTime: 4,
  },
  {
    id: 3,
    title: "Nutrition Guide: Fueling for Match Day",
    excerpt:
      "Learn about the optimal pre-match nutrition strategies to enhance your performance on the field.",
    image: "/optimized/blog/nutrition/nutrition1-large.webp",
    imageFallback: "/optimized/blog/nutrition/nutrition1-large.jpg",
    thumbnail: "/optimized/blog/nutrition/nutrition1-small.webp",
    thumbnailFallback: "/optimized/blog/nutrition/nutrition1-small.jpg",
    category: "Nutrition",
    date: "March 10, 2024",
    readTime: 6,
  },
  {
    id: 4,
    title: "Mental Conditioning in Football",
    excerpt:
      "Understanding the importance of mental strength and how to develop resilience as a footballer.",
    image: "/optimized/blog/lifestyles/lifestyles1-large.webp",
    imageFallback: "/optimized/blog/lifestyles/lifestyles1-large.jpg",
    thumbnail: "/optimized/blog/lifestyles/lifestyles1-small.webp",
    thumbnailFallback: "/optimized/blog/lifestyle/lifestyles1-small.jpg",
    category: "Lifestyle",
    date: "March 8, 2024",
    readTime: 3,
  },
  {
    id: 5,
    title: "Advanced Dribbling Techniques",
    excerpt:
      "Master the art of ball control with these professional dribbling drills and exercises.",
    image: "/optimized/blog/trainings/trainings2-large.webp",
    imageFallback: "/optimized/blog/trainings/training2-large.jpg",
    thumbnail: "/optimized/blog/trainings/training2-small.webp",
    thumbnailFallback: "/optimized/blog/trainings/training2-small.jpg",
    category: "Training",
    date: "March 5, 2024",
    readTime: 7,
  },
  {
    id: 6,
    title: "The Press and Counter-Press",
    excerpt:
      "A detailed analysis of modern pressing systems and how to implement them in your team.",
    image: "/optimized/blog/tactics/tactics2-large.webp",
    imageFallback: "/optimized/blog/tactics/tactics2-large.jpg",
    thumbnail: "/optimized/blog/tactics/tactics2-small.webp",
    thumbnailFallback: "/optimized/blog/tactics/tactics2-small.jpg",
    category: "Tactics",
    date: "March 1, 2024",
    readTime: 5,
  },
];
