export const galleryImages = [
  {
    id: 1,
    category: "Training",
    image: "/optimized/gallery/trainings/training1-normal.webp",
    imageFallback: "/optimized/gallery/trainings/training1-normal.jpg",
    thumbnail: "/optimized/gallery/trainings/training1-thumbnail.webp",
    thumbnailFallback: "/optimized/gallery/trainings/training1-thumbnail.jpg",
    title: "Morning Training Session",
    size: "normal",
  },
  {
    id: 2,
    category: "Matches",
    image: "/optimized/gallery/matches/match1-normal.webp",
    imageFallback: "/optimized/gallery/matches/match1-normal.jpg",
    thumbnail: "/optimized/gallery/matches/match1-thumbnail.webp",
    thumbnailFallback: "/optimized/gallery/matches/match1-thumbnail.jpg",
    title: "Weekend Tournament Final",
    size: "large",
  },
  {
    id: 3,
    category: "Events",
    image: "/optimized/gallery/events/event2-normal.webp",
    imageFallback: "/optimized/gallery/events/event2-normal.jpg",
    thumbnail: "/optimized/gallery/events/event2-thumbnail.webp",
    thumbnailFallback: "/optimized/gallery/events/event2-thumbnail.jpg",
    title: "Annual Academy Day",
    size: "normal",
  },
  {
    id: 4,
    category: "Events",
    image: "/optimized/gallery/events/event1-normal.webp",
    imageFallback: "/optimized/gallery/events/event1-normal.jpg",
    thumbnail: "/optimized/gallery/events/event1-thumbnail.webp",
    thumbnailFallback: "/optimized/gallery/events/event1-thumbnail.jpg",
    title: "Annual Academy Day",
    size: "normal",
  },
  {
    id: 5,
    category: "Events",
    image: "/optimized/gallery/events/event3-normal.webp",
    imageFallback: "/optimized/gallery/events/event3-normal.jpg",
    thumbnail: "/optimized/gallery/events/event3-thumbnail.webp",
    thumbnailFallback: "/optimized/gallery/events/event3-thumbnail.jpg",
    title: "Annual Academy Day",
    size: "normal",
  },
  {
    id: 6,
    category: "Awards",
    image: "/optimized/gallery/awards/award1-normal.webp",
    imageFallback: "/optimized/gallery/awards/award1-normal.jpg",
    thumbnail: "/optimized/gallery/awards/award1-thumbnail.webp",
    thumbnailFallback: "/optimized/gallery/awards/award1-thumbnail.jpg",
    title: "Annual Academy Day",
    size: "normal",
  },
  {
    id: 7,
    category: "Awards",
    image: "/optimized/gallery/awards/award2-normal.webp",
    imageFallback: "/optimized/gallery/awards/award2-normal.jpg",
    thumbnail: "/optimized/gallery/awards/award2-thumbnail.webp",
    thumbnailFallback: "/optimized/gallery/awards/award2-thumbnail.jpg",
    title: "Annual Academy Day",
    size: "normal",
  },
  {
    id: 8,
    category: "Awards",
    image: "/optimized/gallery/awards/award3-normal.webp",
    imageFallback: "/optimized/gallery/awards/award3-normal.jpg",
    thumbnail: "/optimized/gallery/awards/award3-thumbnail.webp",
    thumbnailFallback: "/optimized/gallery/awards/award3-thumbnail.jpg",
    title: "Annual Academy Day",
    size: "normal",
  },
  {
    id: 9, // Fixed duplicate id
    category: "Awards",
    image: "/optimized/gallery/awards/award4-normal.webp",
    imageFallback: "/optimized/gallery/awards/award4-normal.jpg",
    thumbnail: "/optimized/gallery/awards/award4-thumbnail.webp",
    thumbnailFallback: "/optimized/gallery/awards/award4-thumbnail.jpg",
    title: "Annual Academy Day",
    size: "normal",
  },
  {
    id: 10,
    category: "Matches",
    image: "/optimized/gallery/matches/match2-normal.webp",
    imageFallback: "/optimized/gallery/matches/match2-normal.jpg",
    thumbnail: "/optimized/gallery/matches/match2-thumbnail.webp",
    thumbnailFallback: "/optimized/gallery/matches/match2-thumbnail.jpg",
    title: "Weekend Tournament Final",
    size: "large",
  },
  {
    id: 11,
    category: "Matches",
    image: "/optimized/gallery/matches/match3-normal.webp",
    imageFallback: "/optimized/gallery/matches/match3-normal.jpg",
    thumbnail: "/optimized/gallery/matches/match3-thumbnail.webp",
    thumbnailFallback: "/optimized/gallery/matches/match3-thumbnail.jpg",
    title: "Weekend Tournament Final",
    size: "large",
  },
];
